### ISSUE TITLE
csrftoken

### ISSUE THREAD

**Issue by vadimha34** [taile-official/Requests-Register-Instagram#1]
", line 21, in send_sms
    'x-csrftoken': post['csrftoken'],
KeyError: 'csrftoken'

**Comment by xone0** [comment]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\Requests-Register-Instagram-main\main.py", line 73, in <module>
    re.send_sms(phone)
  File "C:\Users\PC\Desktop\Requests-Register-Instagram-main\main.py", line 21, in send_sms
    'x-csrftoken': post['csrftoken'],
KeyError: 'csrftoken'
